# Generated by Django 5.1.1 on 2024-12-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquery',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
