# Generated by Django 5.1.1 on 2024-12-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquery', '0002_alter_enquery_whatsapp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquery',
            name='image',
            field=models.FileField(max_length=250, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='enquery',
            name='whatsapp_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
